name: Playwright Tests

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  SauceDemo:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2

    - name: Set up Docker Buildx
      uses: docker/setup-buildx-action@v1

    - name: Build Docker image
      run: docker build -t playwright-python .

    - name: Restart Docker container
      run: docker start playwright-container

    - name: Run Playwright tests
      run: |
        REPORT_NAME="report_$(date +'%Y-%m-%d_%H-%M-%S').html"
        docker run --name playwright-container playwright-python sh -c "pytest Tests --html=$REPORT_NAME"

    - name: Copy report from Docker container
      run: |
        docker exec playwright-container sh -c 'ls /app/report_*.html' > reports.txt
        while read -r REPORT_NAME; do
          docker cp playwright-container:$REPORT_NAME ${{ github.workspace }}/
        done < reports.txt
        rm reports.txt


    - name: Upload HTML report
      uses: actions/upload-artifact@v2
      with:
        name: html-report
        path: ${{ github.workspace }}/report_*.html
